### ISSUE TITLE
One Hour offset on Upcoming Review forecast

### ISSUE THREAD

**Issue by Travis-Taylor** [Kaniwani/kw-frontend#104]
# KaniWani
This proposes a solution to a discrepancy in the hour presented for reviews in the Upcoming Reviews forecast. I mostly want to make sure my proposed solution makes sense to both of you/isn't missing anything obvious. 

## Issue Type

- [x] Bug (https://github.com/Kaniwani/kw-frontend/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/Kaniwani/kw-frontend/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

The reviews chart on the dashboard lists reviews an hour later than they become available. For instance, see the image taken from my local instance, showing a review with a `next_review_date` of 2020-12-01 06:00:01.061152+00 (or 23:00:01 local time). It places the review at 12:00am rather than 11:00pm.
![current_behavior](https://user-images.githubusercontent.com/20861036/100693336-e145a880-3349-11eb-88e3-7deb85b8bfd5.png)
And the review in question became available at 11pm and not 12am, as expected.
This seems to be caused by [the + 1 on the formatted index](https://github.com/Kaniwani/kw-frontend/blob/6463f0fdbaf166e8f2ce8c9729806a79c8b316c9/app/common/utils/formatUpcomingReviews.js#L8) for the data. I'm not entirely sure what the intent was around that behavior, but removing that +1 causes the review to be listed at 11pm as would be expected:
![remove_padded_hour](https://user-images.githubusercontent.com/20861036/100694897-4353dd00-334d-11eb-9605-af724820aeb4.png)
In digging into the backend a little, it seems that all review dates are set to minute 0 and second 1 on successful quizzing, so I think this change doesn't break any assumptions (i.e. listing a review with review date at hour HH should become available right at HH:00:01)

One note is that this puts the "current" hour at the start of the review forecast, rather than the next upcoming hour. This will either be empty (which is what happens if I just remove the +1 on the frontend data formatting) or could be changed to display all the currently available reviews, representing "upcoming" reviews the user has currently available. Let me know which you prefer, I think it would be easy enough to add the cumulative current reviews, but we could also just drop the current hour from the plot altogether.

## Steps to reproduce

Compare a review's `next_review_date` with its displayed hour on the forecast dashboard.

# Versions

- Node/Yarn: 1.22.5
- Browser: Firefox 83.0

**Comment by DJTB** [comment]
Given a count of 20 in the chart:

So this (used to at least) display that you would have 20 reviews **by** 12am since 5 may actually become available at 11:15pm, 10 at 11:30pm etc

It's possible the scheduling logic has changed since I introduced the chart.
I'm sure I added the +1 since we had the opposite problem where it would say 20 reviews at 11pm, and there would be none when the clock ticked over 😅 

Maybe @tadgh can chime in regarding when the reviews become available.

**Comment by Travis-Taylor** [comment]
Yeah, it occurred to me that we could also change the behavior to change the time they become reviewable to HH:00:00, to avoid "missing a window" for them to be available right at the turn of the hour.

As a user, I always interpreted this chart as showing which reviews would be available at the given hour

**Comment by DJTB** [comment]
I'm all for simplifying it to hour blocks.

**Comment by tadgh** [comment]
Looking at the code now, it appears as though we automatically just truncate to minute 0 and second 1 anyhow. We changed this about a year ago. Reviews always come up on the hour now. I"m fine with this change.

**Comment by Travis-Taylor** [comment]
:+1: Great! 2 questions:
1. Should we remove the "current" hour from the plot then? i.e. the first bar in the chart will represent currently available reviews - we could remove the (empty) spot from the chart:
```
# UpcomingReviewsChart/index.js

<ResponsiveContainer width="100%" minWidth={320} height={300} debounce={100}>
        <BarChart
          data={data.slice(1)}  // <- remove trivial first entry, which goes straight to reviews
          barCategoryGap={2}
          maxBarSize={40}
          margin={{ top: 5, right: 35, left: 20 }}
        >
```
Or we could plot the number ready for review, replacing the first element with the current `reviewsCount`

2. I don't think I have permissions to push up a branch for PR, would you mind adding me?

**Comment by DJTB** [comment]
Had a quick look at your branch, but I think we need to modify the data differently.
With your changes for me at 2:06pm, the chart would start at 4pm - failing to display whatever might be ready for 3pm.

I think this is more what we're after (unless it's shifting the ready reviews into the wrong hour?), could you give it a test?
https://github.com/Kaniwani/kw-frontend/tree/enhancement%2Ffix_forecast_times_alternative
