### ISSUE TITLE
Request for example .env file

### ISSUE THREAD

**Issue by kddude** [Kaniwani/kw-frontend#148]
## Issue Type

- [ ] Bug (https://github.com/Kaniwani/kw-frontend/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [x] Feature (https://github.com/Kaniwani/kw-frontend/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

I'd like to spin up a local instance of WaniKani for development but am in need of an example `.env` file. The README says to contact Duncan on Slack for this (which I did), but given this project isn't as active anymore I'm not sure that the Slack is still in use. Could an example `.env` file be posted in this repo for future reference?

**Comment by DJTB** [comment]
Hey, sorry I didn't see your slack message.
Can you try with the following `.env` - which will run your local against prod.
If you setup a local backend just replace `DEV_DOMAIN=` with your localhost.

```
DEV_DOMAIN=https://www.kaniwani.com
RAVEN_DSN=
SENTRY_AUTH_TOKEN=
SENTRY_ORG=
SENTRY_PROJECT=
```

**Comment by kddude** [comment]
Works perfectly, thank you!
