### ISSUE TITLE
[UI] Dashboard Timeline

### ISSUE THREAD

**Issue by DJTB** [Kaniwani/kw-frontend#24]
Make a timeline similar to rfindley's: [https://www.wanikani.com/chat/api-and-third-party-apps/10751]()

Would have to alter the api response for upcoming reviews to provide grouped results, rather than just the count.

**Comment by Elidrake** [comment]
How is this coming along?  Up for some assistance?

**Comment by DJTB** [comment]
Pretty much complete, just waiting on an update to the server srs count response before closing.

**Comment by DJTB** [comment]
Complete in V2
