### ISSUE TITLE
Allow user to choose default incorrect/correct info level in settings

### ISSUE THREAD

**Issue by DJTB** [Kaniwani/kw-frontend#68]
Incorrect info level: [low, mid, high]
Correct info level: [low, mid, high]

**Comment by tadgh** [comment]
Did you end up implementing this?

**Comment by DJTB** [comment]
I have it ready in a branch.

**Comment by tadgh** [comment]
ah, 99% sure its on the server.

**Comment by DJTB** [comment]
Yeah I see it now, sneaky.

**Comment by tadgh** [comment]
My bad, must have forgotten to give you a heads up.
