### ISSUE TITLE
Implement frontend for maximum_wk_srs_level_to_review option

### ISSUE THREAD

**Issue by tadgh** [Kaniwani/kw-frontend#85]
As detailed in https://github.com/Kaniwani/kw-backend/pull/435

simple profile setting: 
`maximum_wk_srs_level_to_review` which operates in the same fashion as the extant `minimum_wk_srs_level_to_review`, in that it is a partial inequality. Setting it to GURU will include all reviews up to _and including_ guru. `<=`

**Comment by DJTB** [comment]
Added in 2.6.0
