### ISSUE TITLE
New Vocab requires additional data

### ISSUE THREAD

**Issue by DJTB** [Kaniwani/kw-frontend#89]
WK added new words, they are missing pitch accent, parts of speech, sentences etc in KW.
Need to add the additional data to our db for them.

https://community.wanikani.com/t/wanikani-content-update-june-3-2019/37043
https://community.wanikani.com/t/wanikani-content-update-july-4-2019/37588
https://community.wanikani.com/t/wanikani-content-update-july-25-2019/37953

**Comment by DJTB** [comment]
@tadgh I've sent you the updated (full) vocab import on Slack.

**Comment by DJTB** [comment]
@tadgh Did you find out why some of the new words didn't match up / appeared to be missing on import? Are the others that matched all imported on live KW at the moment?

**Comment by tadgh** [comment]
I have not. I'm gonna be doing a full rebuild tomorrow probably, will double check then .

**Comment by tadgh** [comment]
ok, so everything that was in the json was matched, however we have some local vocabulary which still has no english sentence: 
```
river mouth, estuary - かわぐち - 川口 - 2
former years, formerly, a few years ago, previous years, past years, prior years - せんねん - 先年 - 4
abusive language - どくげん - 毒言 - 15
directive, instructions - くんれい - 訓令 - 18
national holiday, festival day - さいじつ - 祭日 - 12
excursion, outing, trip - えんそく - 遠足 - 16
steadily - ちゃくちゃく - 着々 - 12
talented person, clever person - さいじん - 才人 - 2
chrysanthemum - きく - 菊 - 46
pitcher - とうしゅ - 投手 - 8
biography, life story - でんき - 伝記 - 11

```

**Comment by DJTB** [comment]
Yeah, these are vestigial. You can purge them as you see fit.
```
river mouth, estuary - かわぐち - 川口 - 2
former years, formerly, a few years ago, previous years, past years, prior years - せんねん - 先年 - 4
abusive language - どくげん - 毒言 - 15
directive, instructions - くんれい - 訓令 - 18
talented person, clever person - さいじん - 才人 - 2
chrysanthemum - きく - 菊 - 46
```

These are the ones that still exist, and I've sent you the updated vocab on Slack.
```
national holiday, festival day - さいじつ - 祭日 - 12
excursion, outing, trip - えんそく - 遠足 - 16
steadily - ちゃくちゃく - 着々 - 12
pitcher - とうしゅ - 投手 - 8
biography, life story - でんき - 伝記 - 11
```
